@echo off
:: =========================================================================
:: Tool Name: Daily Workspace Launcher Generator
:: Developer: Ben Timothy
:: GitHub: https://github.com/BenTimothyM
:: Description: Native batch script wizard that builds custom automated workspace launcher (.bat) files.
:: =========================================================================

:: -------------------------------------------------------------------------
:: 1. Administrative Privileges Standard Routine
:: -------------------------------------------------------------------------
:: Check for admin rights by requesting session status
net session >nul 2>&1
if %errorLevel% == 0 (
    goto gotAdmin
) else (
    echo Requesting administrative privileges...
    goto UACPrompt
)

:UACPrompt
:: Generate a temporary VBScript to trigger the UAC elevation prompt
echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
echo UAC.ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"
"%temp%\getadmin.vbs"
exit /B

:gotAdmin
:: Clean up the temporary VBScript and set directory scope
if exist "%temp%\getadmin.vbs" ( del "%temp%\getadmin.vbs" )
pushd "%CD%"
CD /D "%~dp0"

:: -------------------------------------------------------------------------
:: 2. UI Initialization & Header Styling
:: -------------------------------------------------------------------------
:: Set professional color scheme (Black background, Light Aqua text)
color 0B
title Daily Workspace Launcher Generator

:WizardStart
cls
echo ===============================================================================
echo                      DAILY WORKSPACE LAUNCHER GENERATOR                      
echo ===============================================================================
echo Created by: Ben Timothy ^| GitHub: https://github.com/BenTimothyM
echo ===============================================================================
echo.

:: -------------------------------------------------------------------------
:: 3. Interactive Wizard Logic
:: -------------------------------------------------------------------------

:: Step 1: Prompt for filename
set "FileName="
set /p "FileName=Enter launcher name (Default: MyWorkspace): "
if "%FileName%"=="" set "FileName=MyWorkspace"

:: Automatically append .bat extension if the user didn't include it
echo %FileName% | findstr /i "\.bat$" >nul
if errorlevel 1 set "FileName=%FileName%.bat"

:: Step 2: Prompt for URLs
set "URL1="
set "URL2="
set "URL3="
echo.
echo Please enter up to 3 website URLs to open automatically.
echo (Leave blank and press Enter to skip any URL)
set /p "URL1=Enter Website URL 1: "
set /p "URL2=Enter Website URL 2: "
set /p "URL3=Enter Website URL 3: "

:: Step 3: Prompt for local directory path
set "FolderPath="
echo.
echo Please enter the full local path for your project or working directory.
echo (Leave blank and press Enter to skip)
set /p "FolderPath=Enter Project Folder Path: "

:: -------------------------------------------------------------------------
:: 4. Script Builder Logic (File Generation)
:: -------------------------------------------------------------------------
echo.
echo Generating your workspace script...

:: Writing code to target script
echo @echo off > "%FileName%"
echo :: ========================================================= >> "%FileName%"
echo :: Generated by Daily Workspace Launcher Generator >> "%FileName%"
echo :: Created by Ben Timothy ^| https://github.com/BenTimothyM >> "%FileName%"
echo :: ========================================================= >> "%FileName%"
echo echo Launching workspace environment... >> "%FileName%"

:: Write URLs to the new script if the user provided them
if not "%URL1%"=="" echo start "" "%URL1%" >> "%FileName%"
if not "%URL2%"=="" echo start "" "%URL2%" >> "%FileName%"
if not "%URL3%"=="" echo start "" "%URL3%" >> "%FileName%"

:: Write Folder Path to the new script if the user provided it
if not "%FolderPath%"=="" (
    :: Using explorer.exe directly to open the directory
    echo start explorer.exe "%FolderPath%" >> "%FileName%"
)

:: Ensure the generated script closes cleanly
echo exit >> "%FileName%"

:: -------------------------------------------------------------------------
:: 5. Success Summary & Post-Generation Options
:: -------------------------------------------------------------------------
cls
echo ===============================================================================
echo                      SUCCESS! WORKSPACE GENERATED
echo ===============================================================================
echo.
echo Your custom automated launcher has been successfully compiled.
echo.
echo File Location: %~dp0%FileName%
echo.
echo What would you like to do next?
echo [1] Launch and Test the New Workspace Immediately
echo [2] Exit
echo.
set /p "Action=Select an option (1 or 2): "

if "%Action%"=="1" (
    :: Launch the newly generated workspace script
    start "" "%FileName%"
    exit
) else (
    exit
)